In [7]:
import numpy as np
from sklearn.metrics import precision_score

In [48]:
a = np.array([[1,0,1], [0,0,1]])
b = np.array([[0,0], [1,0]])

In [19]:
precision_score(a[:, 1], b[:, 1])

/app/miniconda3/envs/main/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.0

In [45]:
def get_non_trivial_targets(gt_test) -> np.ndarray:
    return np.where((gt_test.sum(axis=0) != 0))[0]

def get_masked(mask, *args):
    """in args expect arrays to get masked"""
    tmp = []
    for arg in args:
        tmp.append(arg[:, mask])
    return tuple(tmp)

In [49]:
mask = get_non_trivial_targets(a)

In [50]:
get_masked(mask, a)

(array([[1, 1],
        [0, 1]]),)

In [42]:
a.sum(axis=0) != 0

array([ True, False])

In [41]:
a

array([[1, 0],
       [0, 0]])

In [24]:
b[:, 1]

array([0, 0])

In [25]:
a[:, 1]

array([0, 0])

In [26]:
a

array([[1, 0],
       [0, 0]])

In [27]:
b

array([[0, 0],
       [1, 0]])